adding dcos_image_commit variable
dcos-terraform/terraform-azurerm-dcos pull request #22
Opened 2019-06-21 16:37 UTC by geekbass

2019-06-24 09:31 UTC, fatz requested changes
needs version ref. supporting the new variable

2019-07-02 08:16 UTC, sebbrandt87 requested changes

2019-07-02 08:16 UTC, sebbrandt87 commented on main.tf
> +  # ansible related config
duplicate

see lines 142 to 144

2019-07-02 08:16 UTC, sebbrandt87 commented on scripts/fault-domain-detect.sh
> -set -o nounset -o errexit
Why was it removed?
Actually it will fail if something goes wrong within the script execution. Isn't this what we would expect?

2019-07-02 08:16 UTC, sebbrandt87 commented on variables_dcos_core.tf
> +# variable "role" {
is it a preparation for something?
otherwise please remove ;)

2019-07-02 08:16 UTC, sebbrandt87 commented on variables_dcos_core.tf
> +# DCOS bootstrap node variables
Is this line in the other PROVIDER-dcos modules also?

2019-07-02 14:13 UTC, closed without merging